const translations = {
  cs: {
    'state.idle': 'Nečinný',
    'state.heating': 'Topení',
    'state.cooldown': 'Chlazení',
    'state.vent': 'Větrání',
    'state.error': 'Chyba',
    'temp.current': 'Aktuální',
    'temp.target': 'Cílová',
    'temp.overshoot': 'Překmit',
    'progress.elapsed': 'Uběhlo',
    'progress.remaining': 'Zbývá',
    'learning.title': 'Učení',
    'learning.cycles': 'Cyklů',
    'learning.learned': 'Naučeno',
    'learning.learning': 'Učím se',
    'learning.avg_time': 'Průměrný čas',
    'stats.title': 'Statistiky',
    'stats.total_cycles': 'Celkem cyklů',
    'stats.valid_cycles': 'Platné cykly',
    'stats.success_rate': 'Úspěšnost',
    'stats.avg_heating': 'Průměrná doba topení',
    'stats.avg_overshoot': 'Průměrný překmit',
    'graph.overshoot': 'Historie překmitu',
    'graph.duration': 'Historie doby topení',
    'graph.cycles': 'Cykly',
    'action.reset': 'Reset parametrů',
    'common.minutes': 'min',
    'common.seconds': 's',
  },
  en: {
    'state.idle': 'Idle',
    'state.heating': 'Heating',
    'state.cooldown': 'Cooldown',
    'state.vent': 'Ventilation',
    'state.error': 'Error',
    'temp.current': 'Current',
    'temp.target': 'Target',
    'temp.overshoot': 'Overshoot',
    'progress.elapsed': 'Elapsed',
    'progress.remaining': 'Remaining',
    'learning.title': 'Learning',
    'learning.cycles': 'Cycles',
    'learning.learned': 'Learned',
    'learning.learning': 'Learning',
    'learning.avg_time': 'Avg. Time',
    'stats.title': 'Statistics',
    'stats.total_cycles': 'Total Cycles',
    'stats.valid_cycles': 'Valid Cycles',
    'stats.success_rate': 'Success Rate',
    'stats.avg_heating': 'Avg. Heating Time',
    'stats.avg_overshoot': 'Avg. Overshoot',
    'graph.overshoot': 'Overshoot History',
    'graph.duration': 'Heating Duration History',
    'graph.cycles': 'Cycles',
    'action.reset': 'Reset Parameters',
    'common.minutes': 'min',
    'common.seconds': 's',
  },
};

export function localize(key: string, lang: 'cs' | 'en' = 'cs'): string {
  return translations[lang]?.[key] || key;
}
